import type { Event, User, TicketListing, Order, ExchangeRequest, Notification, Transaction, Review } from "@/types";

export const DEMO_USERS: User[] = [
  {
    id: "u1",
    name: "Priya Sharma",
    email: "priya@example.com",
    avatar: "",
    verified: true,
    rating: 4.8,
    totalSales: 23,
    totalPurchases: 15,
    joinDate: "2025-03-15",
    role: "user",
    city: "Mumbai",
  },
  {
    id: "u2",
    name: "Arjun Mehta",
    email: "arjun@example.com",
    avatar: "",
    verified: true,
    rating: 4.6,
    totalSales: 12,
    totalPurchases: 8,
    joinDate: "2025-06-20",
    role: "user",
    city: "Bangalore",
  },
  {
    id: "u3",
    name: "Neha Gupta",
    email: "neha@example.com",
    avatar: "",
    verified: true,
    rating: 4.9,
    totalSales: 45,
    totalPurchases: 30,
    joinDate: "2024-11-10",
    role: "user",
    city: "Delhi",
  },
  {
    id: "u4",
    name: "Rahul Verma",
    email: "rahul@example.com",
    avatar: "",
    verified: false,
    rating: 4.2,
    totalSales: 5,
    totalPurchases: 3,
    joinDate: "2025-08-01",
    role: "user",
    city: "Hyderabad",
  },
  {
    id: "u5",
    name: "Admin User",
    email: "admin@ticketswapx.com",
    avatar: "",
    verified: true,
    rating: 0,
    totalSales: 0,
    totalPurchases: 0,
    joinDate: "2024-01-01",
    role: "admin",
    city: "Mumbai",
  },
];

const VENUES = {
  mumbai: { id: "v1", name: "Jio World Convention Centre", city: "Mumbai", address: "BKC, Mumbai", capacity: 18000 },
  delhi: { id: "v2", name: "Arun Jaitley Stadium", city: "Delhi", address: "ITO, New Delhi", capacity: 41000 },
  bangalore: { id: "v3", name: "M. Chinnaswamy Stadium", city: "Bangalore", address: "MG Road, Bangalore", capacity: 40000 },
  hyderabad: { id: "v4", name: "Rajiv Gandhi Intl Stadium", city: "Hyderabad", address: "Uppal, Hyderabad", capacity: 55000 },
  chennai: { id: "v5", name: "MA Chidambaram Stadium", city: "Chennai", address: "Chepauk, Chennai", capacity: 50000 },
  pune: { id: "v6", name: "Maharashtra Cricket Stadium", city: "Pune", address: "Gahunje, Pune", capacity: 45000 },
  kolkata: { id: "v7", name: "Eden Gardens", city: "Kolkata", address: "BBD Bagh, Kolkata", capacity: 66000 },
  goa: { id: "v8", name: "PDA Grounds", city: "Goa", address: "Panaji, Goa", capacity: 15000 },
};

export const DEMO_EVENTS: Event[] = [
  {
    id: "e1",
    name: "Coldplay: Music of the Spheres World Tour",
    description: "Experience the magic of Coldplay live! The Music of the Spheres World Tour brings an unforgettable evening of music, light shows, and pure euphoria. Featuring hits from their latest album alongside classic anthems like 'Yellow', 'Fix You', and 'Viva La Vida'.",
    category: "concert",
    date: "2026-11-15",
    time: "19:00",
    venue: VENUES.mumbai,
    image: "/events/coldplay.jpg",
    organizer: "BookMyShow Live",
    basePrice: 4500,
    totalTickets: 18000,
    availableTickets: 24,
    featured: true,
    tags: ["music", "international", "pop", "rock"],
  },
  {
    id: "e2",
    name: "IPL 2026 — MI vs CSK",
    description: "The biggest rivalry in cricket! Mumbai Indians take on Chennai Super Kings in what promises to be an electrifying encounter at the iconic Wankhede Stadium. Don't miss the six-hitting spectacle!",
    category: "cricket",
    date: "2026-10-05",
    time: "19:30",
    venue: VENUES.mumbai,
    image: "/events/ipl-mi-csk.jpg",
    organizer: "BCCI / IPL",
    basePrice: 1500,
    totalTickets: 33000,
    availableTickets: 87,
    featured: true,
    tags: ["cricket", "ipl", "sports", "rivalry"],
  },
  {
    id: "e3",
    name: "Ed Sheeran: +-=÷× Tour",
    description: "Ed Sheeran brings his incredible Mathematics Tour to India! An intimate yet grand evening with the world's biggest singer-songwriter performing all his greatest hits live.",
    category: "concert",
    date: "2026-12-20",
    time: "18:30",
    venue: VENUES.bangalore,
    image: "/events/ed-sheeran.jpg",
    organizer: "BookMyShow Live",
    basePrice: 3500,
    totalTickets: 40000,
    availableTickets: 156,
    featured: true,
    tags: ["music", "international", "pop", "acoustic"],
  },
  {
    id: "e4",
    name: "ISL 2026 — FC Goa vs Kerala Blasters",
    description: "Indian Super League football action! FC Goa host Kerala Blasters in a thrilling South Indian derby under the lights.",
    category: "football",
    date: "2026-10-22",
    time: "20:00",
    venue: VENUES.goa,
    image: "/events/isl-goa.jpg",
    organizer: "ISL",
    basePrice: 500,
    totalTickets: 15000,
    availableTickets: 342,
    featured: false,
    tags: ["football", "sports", "isl", "india"],
  },
  {
    id: "e5",
    name: "Zakir Khan: Tathastu Comedy Tour",
    description: "One of India's beloved comedians, Zakir Khan, returns with his brand-new stand-up special 'Tathastu'. An evening full of laughter, stories, and relatable humor.",
    category: "comedy",
    date: "2026-11-08",
    time: "20:00",
    venue: VENUES.delhi,
    image: "/events/zakir-khan.jpg",
    organizer: "Comedy Central India",
    basePrice: 800,
    totalTickets: 2500,
    availableTickets: 64,
    featured: false,
    tags: ["comedy", "standup", "hindi", "indian"],
  },
  {
    id: "e6",
    name: "Sunburn Festival 2026",
    description: "Asia's largest electronic dance music festival returns to Goa! Three days of non-stop music with world-class DJs, stunning production, and the ultimate beach party vibes.",
    category: "festival",
    date: "2026-12-28",
    time: "16:00",
    venue: VENUES.goa,
    image: "/events/sunburn.jpg",
    organizer: "Sunburn Events",
    basePrice: 5000,
    totalTickets: 50000,
    availableTickets: 520,
    featured: true,
    tags: ["music", "edm", "festival", "goa", "international"],
  },
  {
    id: "e7",
    name: "Ranveer Singh: Simmba Returns Premiere",
    description: "The grand premiere of Bollywood's most anticipated action-comedy! Red carpet event with star appearances and an exclusive first screening.",
    category: "movie",
    date: "2026-11-25",
    time: "19:00",
    venue: VENUES.mumbai,
    image: "/events/simmba.jpg",
    organizer: "Yash Raj Films",
    basePrice: 2000,
    totalTickets: 800,
    availableTickets: 12,
    featured: false,
    tags: ["movie", "bollywood", "premiere", "action"],
  },
  {
    id: "e8",
    name: "TechCrunch India 2026",
    description: "India's premier technology conference bringing together founders, investors, and innovators. Keynotes, workshops, and networking opportunities with the best in tech.",
    category: "conference",
    date: "2026-11-30",
    time: "09:00",
    venue: VENUES.bangalore,
    image: "/events/techcrunch.jpg",
    organizer: "TechCrunch",
    basePrice: 7500,
    totalTickets: 3000,
    availableTickets: 189,
    featured: false,
    tags: ["tech", "conference", "startup", "networking"],
  },
  {
    id: "e9",
    name: "Natyam: Contemporary Dance Theatre",
    description: "A breathtaking fusion of classical Indian dance and contemporary theatre. 'Natyam' tells the story of devotion and transformation through movement and music.",
    category: "theatre",
    date: "2026-12-05",
    time: "19:30",
    venue: VENUES.delhi,
    image: "/events/natyam.jpg",
    organizer: "Natyam Arts Foundation",
    basePrice: 1200,
    totalTickets: 1200,
    availableTickets: 45,
    featured: false,
    tags: ["theatre", "dance", "classical", "arts"],
  },
  {
    id: "e10",
    name: "IPL 2026 — RCB vs KKR",
    description: "Royal Challengers Bangalore take on Kolkata Knight Riders in a high-stakes IPL clash at the Chinnaswamy! Expect high scores and electric atmosphere.",
    category: "cricket",
    date: "2026-10-15",
    time: "19:30",
    venue: VENUES.bangalore,
    image: "/events/ipl-rcb-kkr.jpg",
    organizer: "BCCI / IPL",
    basePrice: 2000,
    totalTickets: 40000,
    availableTickets: 134,
    featured: true,
    tags: ["cricket", "ipl", "sports"],
  },
  {
    id: "e11",
    name: "Arijit Singh Live in Concert",
    description: "The king of playback singing, Arijit Singh, performs his biggest hits live! An emotional evening with soul-stirring melodies from Bollywood's finest voice.",
    category: "concert",
    date: "2026-11-22",
    time: "19:00",
    venue: VENUES.hyderabad,
    image: "/events/arijit.jpg",
    organizer: "Live Nation India",
    basePrice: 2500,
    totalTickets: 25000,
    availableTickets: 89,
    featured: false,
    tags: ["music", "bollywood", "indian", "live"],
  },
  {
    id: "e12",
    name: "Lollapalooza India 2027",
    description: "The legendary Lollapalooza festival lands in India! Multiple stages, dozens of artists across genres — from indie to hip-hop to electronic. The ultimate music experience.",
    category: "festival",
    date: "2027-01-25",
    time: "14:00",
    venue: VENUES.mumbai,
    image: "/events/lolla.jpg",
    organizer: "Lollapalooza India",
    basePrice: 6000,
    totalTickets: 60000,
    availableTickets: 1200,
    featured: true,
    tags: ["music", "festival", "multi-genre", "international"],
  },
];

export const DEMO_LISTINGS: TicketListing[] = [
  {
    id: "l1",
    eventId: "e1",
    event: DEMO_EVENTS[0],
    sellerId: "u1",
    seller: DEMO_USERS[0],
    ticketType: "vip",
    section: "A",
    row: "5",
    seat: "12",
    quantity: 2,
    originalPrice: 8000,
    sellingPrice: 12000,
    verified: true,
    verificationStatus: "verified",
    transferMethod: "instant_transfer",
    status: "active",
    createdAt: "2026-09-01",
    updatedAt: "2026-09-01",
    description: "VIP front-row seats. Selling due to travel conflict.",
    views: 234,
    watchers: 18,
  },
  {
    id: "l2",
    eventId: "e2",
    event: DEMO_EVENTS[1],
    sellerId: "u2",
    seller: DEMO_USERS[1],
    ticketType: "standard",
    section: "B",
    row: "12",
    seat: "45",
    quantity: 4,
    originalPrice: 1500,
    sellingPrice: 2200,
    verified: true,
    verificationStatus: "verified",
    transferMethod: "instant_transfer",
    status: "active",
    createdAt: "2026-09-05",
    updatedAt: "2026-09-05",
    description: "4 tickets together. Great view of the pitch.",
    views: 567,
    watchers: 42,
  },
  {
    id: "l3",
    eventId: "e3",
    event: DEMO_EVENTS[2],
    sellerId: "u3",
    seller: DEMO_USERS[2],
    ticketType: "premium",
    section: "C",
    row: "3",
    seat: "8",
    quantity: 1,
    originalPrice: 5000,
    sellingPrice: 6500,
    verified: true,
    verificationStatus: "verified",
    transferMethod: "manual_transfer",
    status: "active",
    createdAt: "2026-09-08",
    updatedAt: "2026-09-08",
    views: 189,
    watchers: 15,
  },
  {
    id: "l4",
    eventId: "e5",
    event: DEMO_EVENTS[4],
    sellerId: "u4",
    seller: DEMO_USERS[3],
    ticketType: "general",
    quantity: 2,
    originalPrice: 800,
    sellingPrice: 1200,
    verified: false,
    verificationStatus: "pending",
    transferMethod: "meet_at_venue",
    status: "active",
    createdAt: "2026-09-10",
    updatedAt: "2026-09-10",
    description: "Can't make it to the show. Selling at face value + small premium.",
    views: 98,
    watchers: 7,
  },
  {
    id: "l5",
    eventId: "e6",
    event: DEMO_EVENTS[5],
    sellerId: "u1",
    seller: DEMO_USERS[0],
    ticketType: "vip",
    section: "VIP",
    quantity: 2,
    originalPrice: 12000,
    sellingPrice: 15000,
    verified: true,
    verificationStatus: "verified",
    transferMethod: "instant_transfer",
    status: "active",
    createdAt: "2026-09-03",
    updatedAt: "2026-09-03",
    description: "3-day VIP passes with backstage access and lounge entry.",
    views: 445,
    watchers: 38,
  },
  {
    id: "l6",
    eventId: "e10",
    event: DEMO_EVENTS[9],
    sellerId: "u3",
    seller: DEMO_USERS[2],
    ticketType: "standard",
    section: "P1",
    row: "8",
    seat: "22",
    quantity: 3,
    originalPrice: 2000,
    sellingPrice: 3500,
    verified: true,
    verificationStatus: "verified",
    transferMethod: "instant_transfer",
    status: "active",
    createdAt: "2026-09-12",
    updatedAt: "2026-09-12",
    description: "P1 tier seats, amazing view of the pitch. RCB home game atmosphere!",
    views: 312,
    watchers: 27,
  },
  {
    id: "l7",
    eventId: "e11",
    event: DEMO_EVENTS[10],
    sellerId: "u2",
    seller: DEMO_USERS[1],
    ticketType: "premium",
    section: "S1",
    row: "2",
    seat: "5",
    quantity: 2,
    originalPrice: 4000,
    sellingPrice: 5500,
    verified: true,
    verificationStatus: "verified",
    transferMethod: "instant_transfer",
    status: "active",
    createdAt: "2026-09-11",
    updatedAt: "2026-09-11",
    description: "Premium seats, second row! Arijit Singh performing all the classics.",
    views: 278,
    watchers: 22,
  },
  {
    id: "l8",
    eventId: "e7",
    event: DEMO_EVENTS[6],
    sellerId: "u4",
    seller: DEMO_USERS[3],
    ticketType: "standard",
    quantity: 1,
    originalPrice: 2000,
    sellingPrice: 5000,
    verified: false,
    verificationStatus: "pending",
    transferMethod: "meet_at_venue",
    status: "active",
    createdAt: "2026-09-13",
    updatedAt: "2026-09-13",
    description: "Red carpet premiere access. Limited seats available.",
    views: 567,
    watchers: 45,
  },
];

export const DEMO_ORDERS: Order[] = [
  {
    id: "o1",
    listingId: "l2",
    listing: DEMO_LISTINGS[1],
    buyerId: "u3",
    buyer: DEMO_USERS[2],
    sellerId: "u2",
    seller: DEMO_USERS[1],
    quantity: 4,
    totalPrice: 8800,
    platformFee: 880,
    sellerPayout: 7920,
    paymentMethod: "upi",
    paymentStatus: "completed",
    orderStatus: "completed",
    createdAt: "2026-09-06",
    updatedAt: "2026-09-06",
    transactionId: "TXN-20260906-001",
    transferCode: "TSX-ABCD-1234",
  },
  {
    id: "o2",
    listingId: "l5",
    listing: DEMO_LISTINGS[4],
    buyerId: "u4",
    buyer: DEMO_USERS[3],
    sellerId: "u1",
    seller: DEMO_USERS[0],
    quantity: 2,
    totalPrice: 30000,
    platformFee: 3000,
    sellerPayout: 27000,
    paymentMethod: "card",
    paymentStatus: "completed",
    orderStatus: "transferred",
    createdAt: "2026-09-04",
    updatedAt: "2026-09-05",
    transactionId: "TXN-20260904-002",
    transferCode: "TSX-EFGH-5678",
  },
  {
    id: "o3",
    listingId: "l1",
    listing: DEMO_LISTINGS[0],
    buyerId: "u4",
    buyer: DEMO_USERS[3],
    sellerId: "u1",
    seller: DEMO_USERS[0],
    quantity: 2,
    totalPrice: 24000,
    platformFee: 2400,
    sellerPayout: 21600,
    paymentMethod: "upi",
    paymentStatus: "pending",
    orderStatus: "payment_processing",
    createdAt: "2026-09-14",
    updatedAt: "2026-09-14",
    transactionId: "TXN-20260914-003",
  },
];

export const DEMO_EXCHANGES: ExchangeRequest[] = [
  {
    id: "ex1",
    requesterId: "u3",
    requester: DEMO_USERS[2],
    requesterListingId: "l3",
    requesterListing: DEMO_LISTINGS[2],
    targetListingId: "l7",
    targetListing: DEMO_LISTINGS[6],
    message: "I'd love to swap my Ed Sheeran ticket for Arijit Singh! Both premium seats.",
    status: "pending",
    createdAt: "2026-09-13",
    updatedAt: "2026-09-13",
  },
  {
    id: "ex2",
    requesterId: "u2",
    requester: DEMO_USERS[1],
    requesterListingId: "l6",
    requesterListing: DEMO_LISTINGS[5],
    targetListingId: "l4",
    targetListing: DEMO_LISTINGS[3],
    message: "I have RCB vs KKR tickets. Would love to trade for the Zakir Khan show!",
    status: "accepted",
    createdAt: "2026-09-11",
    updatedAt: "2026-09-12",
  },
];

export const DEMO_NOTIFICATIONS: Notification[] = [
  {
    id: "n1",
    userId: "u1",
    type: "sale",
    title: "Ticket Sold!",
    message: "Your Coldplay VIP tickets have been purchased by a buyer.",
    read: false,
    createdAt: "2026-09-14T10:30:00",
    actionUrl: "/dashboard/transactions",
  },
  {
    id: "n2",
    userId: "u1",
    type: "payment",
    title: "Payment Received",
    message: "₹21,600 has been credited to your account for order #o1.",
    read: false,
    createdAt: "2026-09-14T11:00:00",
    actionUrl: "/dashboard/transactions",
  },
  {
    id: "n3",
    userId: "u2",
    type: "exchange_request",
    title: "New Exchange Request",
    message: "Neha wants to exchange her Ed Sheeran ticket for your Arijit Singh ticket.",
    read: true,
    createdAt: "2026-09-13T14:00:00",
    actionUrl: "/dashboard/exchanges",
  },
  {
    id: "n4",
    userId: "u3",
    type: "verification",
    title: "Ticket Verified",
    message: "Your Sunburn Festival VIP listing has been verified and is now live.",
    read: true,
    createdAt: "2026-09-03T09:15:00",
  },
  {
    id: "n5",
    userId: "u4",
    type: "event_reminder",
    title: "Event in 3 Weeks",
    message: "IPL 2026 — MI vs CSK is happening on Oct 5. Don't forget!",
    read: false,
    createdAt: "2026-09-14T08:00:00",
    actionUrl: "/events/e2",
  },
];

export const DEMO_TRANSACTIONS: Transaction[] = [
  {
    id: "t1",
    orderId: "o1",
    userId: "u3",
    amount: 8800,
    fee: 880,
    netAmount: 7920,
    type: "purchase",
    status: "completed",
    paymentMethod: "upi",
    createdAt: "2026-09-06",
  },
  {
    id: "t2",
    orderId: "o1",
    userId: "u2",
    amount: 8800,
    fee: 880,
    netAmount: 7920,
    type: "sale",
    status: "completed",
    paymentMethod: "upi",
    createdAt: "2026-09-06",
  },
  {
    id: "t3",
    orderId: "o2",
    userId: "u4",
    amount: 30000,
    fee: 3000,
    netAmount: 27000,
    type: "purchase",
    status: "completed",
    paymentMethod: "card",
    createdAt: "2026-09-04",
  },
  {
    id: "t4",
    orderId: "o2",
    userId: "u1",
    amount: 30000,
    fee: 3000,
    netAmount: 27000,
    type: "payout",
    status: "completed",
    paymentMethod: "upi",
    createdAt: "2026-09-05",
  },
];

export const DEMO_REVIEWS: Review[] = [
  {
    id: "r1",
    reviewerId: "u3",
    revieweeId: "u2",
    orderId: "o1",
    rating: 5,
    comment: "Perfect tickets! Great communication and instant transfer. Highly recommend this seller!",
    createdAt: "2026-09-07",
  },
  {
    id: "r2",
    reviewerId: "u4",
    revieweeId: "u1",
    orderId: "o2",
    rating: 5,
    comment: "VIP passes worked perfectly. Smooth transaction. Thank you!",
    createdAt: "2026-09-06",
  },
  {
    id: "r3",
    reviewerId: "u1",
    revieweeId: "u4",
    orderId: "o2",
    rating: 4,
    comment: "Quick payment, easy to work with. Would sell to again.",
    createdAt: "2026-09-06",
  },
];

export const EVENT_CATEGORIES: { value: string; label: string; icon: string }[] = [
  { value: "concert", label: "Concerts", icon: "🎵" },
  { value: "cricket", label: "Cricket", icon: "🏏" },
  { value: "football", label: "Football", icon: "⚽" },
  { value: "comedy", label: "Comedy", icon: "😂" },
  { value: "festival", label: "Festivals", icon: "🎪" },
  { value: "movie", label: "Movies", icon: "🎬" },
  { value: "conference", label: "Conferences", icon: "🎤" },
  { value: "theatre", label: "Theatre", icon: "🎭" },
  { value: "other", label: "Other", icon: "✨" },
];

export const INDIAN_CITIES = [
  "Mumbai",
  "Delhi",
  "Bangalore",
  "Hyderabad",
  "Chennai",
  "Pune",
  "Kolkata",
  "Ahmedabad",
  "Jaipur",
  "Goa",
  "Lucknow",
  "Chandigarh",
];

export const ADMIN_STATS = {
  totalUsers: 12847,
  activeListings: 3256,
  ticketsSold: 28934,
  gmv: 184500000,
  platformRevenue: 18450000,
  successfulExchanges: 4521,
  failedTransactions: 89,
  reportedListings: 23,
};

export const ADMIN_CHARTS_DATA = {
  dailySales: [
    { date: "Sep 1", sales: 45, revenue: 234000 },
    { date: "Sep 2", sales: 52, revenue: 312000 },
    { date: "Sep 3", sales: 38, revenue: 189000 },
    { date: "Sep 4", sales: 61, revenue: 423000 },
    { date: "Sep 5", sales: 55, revenue: 378000 },
    { date: "Sep 6", sales: 48, revenue: 298000 },
    { date: "Sep 7", sales: 72, revenue: 512000 },
    { date: "Sep 8", sales: 67, revenue: 467000 },
    { date: "Sep 9", sales: 83, revenue: 589000 },
    { date: "Sep 10", sales: 91, revenue: 634000 },
    { date: "Sep 11", sales: 76, revenue: 534000 },
    { date: "Sep 12", sales: 88, revenue: 612000 },
    { date: "Sep 13", sales: 94, revenue: 678000 },
    { date: "Sep 14", sales: 102, revenue: 745000 },
  ],
  categoryDistribution: [
    { name: "Concerts", value: 35, fill: "#6366f1" },
    { name: "Cricket", value: 28, fill: "#f59e0b" },
    { name: "Football", value: 12, fill: "#10b981" },
    { name: "Comedy", value: 8, fill: "#ef4444" },
    { name: "Festivals", value: 10, fill: "#8b5cf6" },
    { name: "Other", value: 7, fill: "#64748b" },
  ],
  cityDistribution: [
    { city: "Mumbai", listings: 1245 },
    { city: "Delhi", listings: 987 },
    { city: "Bangalore", listings: 876 },
    { city: "Hyderabad", listings: 654 },
    { city: "Chennai", listings: 432 },
    { city: "Pune", listings: 321 },
    { city: "Kolkata", listings: 298 },
  ],
  userGrowth: [
    { month: "Apr", users: 2340 },
    { month: "May", users: 3456 },
    { month: "Jun", users: 4890 },
    { month: "Jul", users: 6234 },
    { month: "Aug", users: 8901 },
    { month: "Sep", users: 12847 },
  ],
};
